name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Fazer build
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v3
